improved defaults and improved flow demonstration
pycaret/pycaret pull request #1242
Opened 2021-05-11 12:06 UTC by ngupta23

## Related Issuse or bug
  - Improved the defaults in create_model for time series.

Fixes: 
  - Set default trend to "add" (most models have None). Rationale: If trend is not present, "slope" equivalent in model will be small 
  - If seasonality is detected, Set default seasonal model to multiplicative. Rationale: If seasonality is additive, then the multiplicative component will be small

## Type of change

Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Unit test pass

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2021-05-11 12:12 UTC, Yard1 requested changes
Just small nitpicks

2021-05-11 12:36 UTC, ngupta23 commented on pycaret/containers/models/time_series.py
> +                "error": ["add", "mul"],
Plus I prefer it to be explicit so it is easier to read :)

2021-05-11 14:24 UTC, TremaMiguel approved these changes

2021-05-11 14:28 UTC, TremaMiguel commented
Just one thing, next meeting I will like to discuss if there's a better way to test the tuning methods, currently the CI takes more than an hour and most of the time testing the time_series module. Here is an image of `test_tune_model_random` durations. 

![test_random](https://user-images.githubusercontent.com/49818188/117832355-09133380-b23b-11eb-9544-6e35b34efb6b.png)

2021-05-12 20:50 UTC, Yard1 approved these changes

2021-05-12 21:29 UTC, ngupta23 commented on pycaret/containers/models/time_series.py
> +        args.update({"trend": "add"})
Ok, I have updated it now.

2021-05-12 21:37 UTC, merged