feat: Tbats and bats models
pycaret/pycaret pull request #1243
Opened 2021-05-11 15:05 UTC by TremaMiguel

#### Describe the changes you've made

Major changes include: 

1. `TBATS` and `BATS` models containers. [link](https://github.com/pycaret/pycaret/blob/a3fd296b8b4ca74ead5141caeadd1819faef98f6/pycaret/containers/models/time_series.py#L582)
2. `TBATS` and `BATS` examples in notebook. [link](https://github.com/pycaret/pycaret/blob/a3fd296b8b4ca74ead5141caeadd1819faef98f6/time_series_101.ipynb)

Minor changes include:

1. On class container initialization call `args`, `tune_args`, `tune_grid` and `tune_distributions` are called through methods that can be accessed as attributes. [link](https://github.com/pycaret/pycaret/blob/a3fd296b8b4ca74ead5141caeadd1819faef98f6/pycaret/containers/models/time_series.py#L595).
2. Filter `UserWarning` and `ConvergenceWarning` in time series testing. [link](https://github.com/pycaret/pycaret/blob/a3fd296b8b4ca74ead5141caeadd1819faef98f6/pycaret/tests/test_time_series.py#L193)
3. For blend methods test only a subset of the models, tests take too long. [link](https://github.com/pycaret/pycaret/blob/a3fd296b8b4ca74ead5141caeadd1819faef98f6/pycaret/tests/test_time_series.py#L200).
4. Fix `AttributeError: 'float' object has no attribute 'round'`. [link](https://github.com/pycaret/pycaret/blob/a3fd296b8b4ca74ead5141caeadd1819faef98f6/pycaret/utils.py#L85)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

No new tests needed.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2021-05-11 19:54 UTC, Yard1 requested changes
There are a lot of formatting changes, I think you may have different black settings that the rest of us - we'll need to figure that out

2021-05-11 22:06 UTC, TremaMiguel commented on pycaret/tests/test_time_series.py
> +    ts_models = list(np.random.choice(load_models, 5))
yes, I agree, maybe the more critical ones, excluding random forest, tbats and bats as they take too long.

2021-05-12 00:00 UTC, Yard1 commented on pycaret/tests/test_time_series.py
> +    ts_models = list(np.random.choice(load_models, 5))
Sounds fine to me

2021-05-12 03:27 UTC, TremaMiguel commented on pycaret/tests/test_time_series.py
> +    ts_models = list(np.random.choice(load_models, 5))
FYI these are the ones I'm picking for  `test_blend_model` and `test_blend_model_predict` 

```python
_BLEND_TEST_MODELS = [
    'naive',
    'poly_trend',
    'arima'
    'auto_ets',
    'lr_cds_dt',
    'en_cds_dt',
    'knn_cds_dt',
    'dt_cds_dt',
    'lightgbm_cds_dt'
]
```
2 baseline models, 2 classical statistical, two regress, 2 linear model based, 1 neighbors based, 1 tree based, 1 gradient boosting based

2021-05-12 09:41 UTC, Yard1 approved these changes
It looks like numpy is not imported in `pycaret/utils.py`, can you fix? Aside from that LGTM

2021-05-12 14:07 UTC, ngupta23 approved these changes

2021-05-12 14:07 UTC, merged