Add support for CUDA version of LightGBM
pycaret/pycaret pull request #1396
Opened 2021-06-25 04:00 UTC by IncubatorShokuhou

## Related Issuse or bug
This PR adds support for CUDA version of LightGBM.

#### Describe the changes you've made
At present, PyCaret only supports OpenCL version of LightGBM( as introduced in `PyCaret on GPU` of `README.md`.
Actually, LightGBM also supports a (experimental) CUDA version(https://github.com/microsoft/LightGBM/tree/master/python-package). To use CUDA version, we only need to set `device="gpu"` in `LGBMRegressor`\`LGBMClassifier`.
I made some changes in `containers/models/classification.py`/`containers/models/regression.py` to make LightGBM works properly when `gpu_param=True` or  `gpu_param="force"` ,when CUDA version, instead of OpenCL version, of LightGBM is installed.
PS: 
- To compile CUDA version: `pip install lightgbm --install-option=--cuda`
- I don't know if information related to LightGBM on GPU should be changed in README/User guide etc. So I only changed the code.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

2021-06-25 09:02 UTC, IncubatorShokuhou commented
Sorry, I accidently pushed another commit (which fixed https://github.com/pycaret/pycaret/issues/1394) in a same PR...

2021-06-26 11:57 UTC, Yard1 commented
@IncubatorShokuhou we can keep it here

2021-06-26 12:02 UTC, Yard1 requested changes
This would need to be documented in `setup()`, but I am not sure it's a good idea. Would it be possible to do the following logic:
if `use_gpu is True` and the `cuda` version can be used (no exception), use that
otherwise, try the `gpu` version

2021-06-26 12:02 UTC, Yard1 commented on pycaret/containers/models/classification.py
> +def CompareVersion(version1: str, version2: str) -> int:\
Can this be also moved to `pycaret.utils`?

2021-06-26 12:02 UTC, Yard1 commented on pycaret/containers/models/regression.py
> +def CompareVersion(version1: str, version2: str) -> int:\
Move to pycaret.utils and use the same method everywhere

2021-06-26 12:55 UTC, IncubatorShokuhou commented
> This would need to be documented in `setup()`, but I am not sure it's a good idea. Would it be possible to do the following logic:
> if `use_gpu is True` and the `cuda` version can be used (no exception), use that
> otherwise, try the `gpu` version

I would like to suggest to use opencl version before cuda version, as cuda version is comparatively experimental according to LightGBM's document.

2021-06-28 01:23 UTC, IncubatorShokuhou commented on pycaret/containers/models/classification.py
> +    v1, v2 = ([*map(int, v.split('.'))] for v in (version1, version2))
Done. The method of comparing version have been changed to `packaging.version`. BTW, do I need to change the version comparision methods in `xgboost` and `catboost` containers as well?

2021-06-30 04:27 UTC, IncubatorShokuhou commented
In addition to `pycaret/containers/models/regression.py` and `pycaret/containers/models/classification.py`, I also modified the version comparison method in `pycaret/internal/tabular.py`, which are all scripts includes version comparsion that can I can find.

2021-06-30 04:30 UTC, IncubatorShokuhou commented
> I would like to suggest to try opencl version before cuda version, as cuda version is comparatively experimental according to LightGBM's document.

So I think maybe my  logic in scripts are ok and do not need to be changed, isn't it?

2021-06-30 10:09 UTC, Yard1 commented
@IncubatorShokuhou This looks good. Have you tested it yourself? We don't have CI for GPU.

2021-06-30 11:20 UTC, IncubatorShokuhou commented
> @IncubatorShokuhou This looks good. Have you tested it yourself? We don't have CI for GPU.

Yes, I have tested it on a V100 GPU (from aws), and everything works well.

2021-06-30 11:53 UTC, Yard1 approved these changes
Thanks!

2021-06-30 11:53 UTC, merged