Add new model explaination algorithms for interpret_model
pycaret/pycaret pull request #1415
Opened 2021-06-30 15:02 UTC by IncubatorShokuhou

## Related Issuse or bug
  - Add new interpret_model methods

#### Describe the changes you've made
Now in PyCaret, `interpret_model` method supports 4 model interpretation methods:
 - `summary` - Summary Plot using SHAP
 - `correlation` - Dependence Plot using SHAP
 - `reason` - Force Plot using SHAP
 - `pdp` - Partial Dependence Plot

In this PR, two more methods (based on  [interpret](https://github.com/interpretml/interpret) and [interpret-community](https://github.com/interpretml/interpret-community)) are added to `interpret_model`, to help people better understanding the model:
 - `msa` - Morris Sensitivity Analysis
 - `pfi` - Permutation Feature Importance

Also, the origin `pdp` is also replaced with the implementation in `interpret`, which shows more information and more interactive (returns plotly figure, can be saved into html).

Errors in using data in `pdp` (`X_train` -> `test_X`) have also been fixed.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

2021-07-02 12:49 UTC, pycaret commented
@IncubatorShokuhou This is really great. We should try our best to get this included in the `2.3.2` release. 

Thank you so much!

2021-07-06 22:26 UTC, Yard1 requested changes

2021-07-06 22:26 UTC, Yard1 commented on pycaret/internal/tabular.py
> +            import interpret
```suggestion
            from interpret.blackbox import MorrisSensitivity
```

2021-07-06 22:26 UTC, Yard1 commented on pycaret/internal/tabular.py
> +            import interpret
```suggestion
            from interpret.blackbox import PartialDependence
```

2021-07-06 22:26 UTC, Yard1 commented on pycaret/internal/tabular.py
> +            import interpret
```suggestion
            from interpret.ext.blackbox import PFIExplainer
```

2021-07-06 22:26 UTC, Yard1 commented on pycaret/internal/tabular.py
> +                "interpret-community library not found. pip install interpret-community to generate msa plot in interpret_model function."
```suggestion
                "interpret-community library not found. pip install interpret-community to generate pfi plot in interpret_model function."
```

2021-07-06 22:26 UTC, Yard1 commented on pycaret/internal/tabular.py
> +                "interpret-community library not found. pip install interpret-community to generate msa plot in interpret_model function."
```suggestion
                "interpret-community library not found. pip install interpret-community to generate pfi plot in interpret_model function."
```

2021-07-06 23:52 UTC, Yard1 approved these changes
Thanks!

2021-07-06 23:52 UTC, merged