Modified save argument of plot_model()
pycaret/pycaret pull request #1537
Opened 2021-08-26 16:02 UTC by bhanuteja2001

## Enchancement #1288 
  - Enhanced the plot_model function to save the figure at any destination in the system. 

#### Describe the changes you've made
Modified the save argument of plot_model to save the figure at the destination mentioned by the user. Instead of just saving the figure in the current directory.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Tested with the confusion matrix plot.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original picture of Log file         | Picture saved at the destination mentioned
 :--------------------: |:--------------------:
 **![Screenshot (422)_LI](https://user-images.githubusercontent.com/44323155/131104602-d19bfb6d-3bd2-40de-8c0f-bdcbd2ba6ec4.jpg)**  | <b>
![Screenshot (418)](https://user-images.githubusercontent.com/44323155/131105006-e09e9f42-ae82-45ad-9acf-8f88837d8d14.png)
 </b> |
 
![Screenshot (420)](https://user-images.githubusercontent.com/44323155/131105112-2f3a99d3-4154-45bf-af35-738ec37bce26.png)

2021-09-01 21:22 UTC, Yard1 commented
Hey @bhanuteja2001 thank you for doing this. Could we do something like this instead?:
```python
        if isinstance(save, str):
            visualizer.show(outpath=f"{name}.png", clear_figure=True)
        else:
            logger.info(f"Saving '{name}.png' in the path specified")
            plt.savefig("{}/{}.png".format(save,name))

2021-09-02 03:32 UTC, bhanuteja2001 commented
@Yard1  sure let's do it this way

2021-09-02 09:11 UTC, bhanuteja2001 commented
@Yard1 I have made the changes.
Please check now.

2021-09-03 00:29 UTC, Yard1 requested changes
Thanks! Just a few more comments. Happy to merge once those are addressed and CI passes 🚀

2021-09-03 00:29 UTC, Yard1 commented on pycaret/internal/tabular.py
> +                    if not isinstance(save, bool):
Indentation

2021-09-03 00:29 UTC, Yard1 commented on pycaret/internal/tabular.py
> +                    if not isinstance(save, bool):
Indentation

2021-09-03 00:29 UTC, Yard1 commented on pycaret/internal/tabular.py
> +            if save == True:
Missed here

2021-09-03 00:29 UTC, Yard1 commented on pycaret/internal/tabular.py
> +            if save == True:
Missed here

2021-09-03 05:02 UTC, bhanuteja2001 commented
@Yard1 please check now.
I have made the changes as requested.

2021-09-04 13:58 UTC, Yard1 approved these changes

2021-09-04 13:58 UTC, merged