Fugue for PyCaret3
pycaret/pycaret pull request #2604
Opened 2022-05-30 00:50 UTC by goodwanghan

## Related Issue or bug

https://github.com/pycaret/pycaret/issues/2452

Closes #2452 

#### Describe the changes you've made

Add Fugue parallel backend to PyCaret 3

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Not tested yet

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2022-05-30 17:10 UTC, ngupta23 reviewed
Could you delete AUC.png? It is probably created when you run the tests.

2022-05-30 17:22 UTC, goodwanghan commented
> Could you delete AUC.png? It is probably created when you run the tests.

Done

2022-05-30 22:00 UTC, Yard1 requested changes
Thanks, this is great! I have a few comments.

2022-05-31 05:44 UTC, goodwanghan commented on pycaret/internal/parallel/parallel_backend.py
> +        return False
DOne

2022-05-31 05:44 UTC, goodwanghan commented on pycaret/classification/oop.py
> +        display: Optional[CommonDisplay] = None,
Removed

2022-05-31 06:04 UTC, goodwanghan commented on pycaret/internal/pycaret_experiment/pycaret_experiment.py
> +        }
Done

2022-05-31 06:04 UTC, goodwanghan commented on pycaret/classification/oop.py
> +        assert (data is None and data_func is not None) or (
Done

2022-05-31 14:02 UTC, merged