Deleted unnecessary branching
pycaret/pycaret pull request #562
Opened 2020-08-28 11:20 UTC by MattiaVerticchio

2020-08-28 11:23 UTC, Yard1 commented on pycaret/classification.py
> +        df = df[df.index.isin(model_type.get(type))]
Is this going to work correctly if `type` is None?

2020-08-28 13:21 UTC, Yard1 commented
Yeah, this doesn't work, @MattiaVerticchio. Check the CI please.

2020-08-28 17:13 UTC, MattiaVerticchio commented
Now it should work, I added a default `df.index`, so that returns the input DataFrame when `type` is not in the three specified, including `None`.

2020-08-28 17:22 UTC, Yard1 commented
Can you make it throw an exception if the type is not one of those three or None?

2020-08-28 19:41 UTC, MattiaVerticchio commented
Done

2020-08-28 19:42 UTC, Yard1 commented
Great, thanks. Gonna wait for CI and merge

2020-08-28 20:21 UTC, Yard1 requested changes

2020-08-28 20:21 UTC, Yard1 commented on pycaret/classification.py
> +    return df[df.index.isin(model_type.get(type, df.index))]
needs an indent

2020-08-28 21:16 UTC, Yard1 requested changes

2020-08-28 21:16 UTC, Yard1 commented on pycaret/classification.py
> +        if type not in list(model_type):
in list or None, please

2020-08-29 10:37 UTC, MattiaVerticchio commented on pycaret/classification.py
> +        if type not in list(model_type):
Added `None` as a valid value.

2020-08-29 10:48 UTC, merged

2020-08-29 10:48 UTC, Yard1 commented
Thanks for working on this, @MattiaVerticchio.