Simplifying bool checks and fixing type hints
pycaret/pycaret pull request #580
Opened 2020-09-01 08:20 UTC by MattiaVerticchio

I set a single loop for all the boolean parameters to check via `isinstance(parameter, bool)` and fixed missing `Dict` and `Optional` imports from `typing`.

2020-09-01 09:37 UTC, Yard1 requested changes

2020-09-01 09:37 UTC, Yard1 commented on pycaret/classification.py
> +        if not isinstance(eval(param), float) or not 0 < eval(param) < 1:
Is it a good idea to use `eval` here? It's not a web app, so it's not probably a huge security risk, but it doesn't sit well with me. You could just do `locals()['param']` instead. `locals()` and `globals()` return dictionaries of currently set local and global variables in the form `name : value`.

2020-09-01 09:37 UTC, Yard1 commented on pycaret/classification.py
> +    if use_gpu is not "Force" and not isinstance(use_gpu, bool):
Identity comparison (is) serves a different purpose than value comparison (==). The latter should be used for strings.

2020-11-01 17:31 UTC, pycaret commented
@Yard1 Do we still need this PR? can we close it?

2020-11-01 18:55 UTC, closed without merging