improve pandas dataframe checking
pycaret/pycaret pull request #971
Opened 2020-12-29 21:37 UTC by gcamargo1

Here's a suggestion to guarantee a positive pandas dataframe.

2021-01-01 19:22 UTC, Yard1 requested changes
Thanks for your contribution. I just have a few nitpicks.

2021-01-01 19:22 UTC, Yard1 commented on pycaret/internal/tabular.py
> +    if train_size <= 0:
Would it also be possible to make sure it's not bigger than 1?

2021-01-01 19:22 UTC, Yard1 commented on pycaret/internal/tabular.py
> +            f"Target parameter: {target} does not exist in the data" f" provided."
`data" f" provided."` to  `data provided."`

2021-01-01 19:22 UTC, Yard1 commented on pycaret/internal/tabular.py
> +            "imputation_type parameter only accepts 'simple' or " "'iterative'."
`or " "'iterative'."` to `or 'iterative'."`

2021-01-01 19:22 UTC, Yard1 commented on pycaret/internal/tabular.py
> +        raise TypeError("rare_level_threshold parameter must be a float")
This could be just one check (one if for float + range)

2021-01-03 03:39 UTC, gcamargo1 commented
Hi @Yard1 , tried to address all of your comments, please let me know if it makes sense to you.

2021-01-07 22:27 UTC, Yard1 commented
@gcamargo1 Thanks for your contribution.

2021-01-07 22:27 UTC, merged

2021-01-14 04:42 UTC, gcamargo1 commented
@Yard1 , I use black, which I'm not sure if it deals in the docstring.